Feature/person tab
FabrizioSposetti-U/viper-ios pull request #3
Opened 2019-10-17 00:53 UTC by FabrizioSposetti-U

Add navigation builder

Add TabModule

Add PersonSearchModule with search bar implemented

2019-10-18 14:09 UTC, ignaciohug0g commented on TvMaze/Modules/PersonSearch/View/PersonSearchViewController.swift
> +        tableView.separatorColor = UIColor.black
podríamos definir lo siguiente:

```
protocol NibLoadableView: class {
    static var nibName: String { get }
}

extension NibLoadableView where Self: UIView {
    static var nibName: String {
        return String(describing: self)
    }
}
```

para luego extender a una `UITableViewCell`

`extension UITableViewCell: ReusableView { }`

De esta forma no necesitaríamos el `nibName` en cada `UITableViewCell`.

Luego podemos definir:

```
extension UITableView {
    
    func register<T: UITableViewCell>(_: T.Type) {
        
        let nib = UINib(nibName: T.nibName, bundle: nil)
        register(nib, forCellReuseIdentifier: T.reuseIdentifier)
    }
    
    func dequeueReusableCell<T: UITableViewCell>(forIndexPath indexPath: IndexPath) -> T {
        guard let cell = dequeueReusableCell(withIdentifier: T.reuseIdentifier, for: indexPath) as? T else {
            fatalError("Could not dequeue cell with identifier: \(T.reuseIdentifier)")
        }
        return cell
    }
}
```

que te parece?

2019-10-18 14:12 UTC, ignaciohug0g commented on TvMaze/Utils/Extensions/UIViewController+Extension.swift
> +        guard let url = URL(string: url ?? "") else {
por alguna razón este método esta en un extension de `UIViewController`?

2019-10-18 14:18 UTC, ignaciohug0g commented on TvMaze/Utils/DataManager/API/ShowsDataMangerAPI.swift
> +        return APIClient.executeRequest(request: APIRouter.persons(name: name))
ahora esta clase se encarga no solo de todo lo referido a shows, sino también de las personas... quizá sea momento de crear una clase aparte para este último

como lo veo `ShowsDataManagerAPI` sería un `repository` con lo cual tampoco veo mal renombrarlo, algo así como `ShowRepository`, que opinas?

2019-10-18 14:21 UTC, ignaciohug0g requested changes
Me gusta cómo lo estás encarando. Los comments son más que nada detalles de cómo tenemos hecho algunas cosas en el proyecto.

2019-10-18 17:04 UTC, FabrizioSposetti-U commented on TvMaze/Modules/PersonSearch/View/PersonSearchViewController.swift
> +        tableView.separatorColor = UIColor.black
Excelente !

2019-10-18 17:04 UTC, FabrizioSposetti-U commented on TvMaze/Utils/Extensions/UIViewController+Extension.swift
> +        guard let url = URL(string: url ?? "") else {
Lo moví a un helper... tiene mas sentido

2019-10-18 17:05 UTC, FabrizioSposetti-U commented on TvMaze/Utils/DataManager/API/ShowsDataMangerAPI.swift
> +        return APIClient.executeRequest(request: APIRouter.persons(name: name))
Ahí renombré a ShowRepository y cree PersonRepository (para manejar las llamadas de las personas).
Cada cual implementa su correspondiente protocolo

2019-10-21 13:59 UTC, ignaciohug0g approved these changes

2019-10-21 14:02 UTC, merged